# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: CC-BY-SA-4.0
# ==-----------------------------------------------------------== #

# Reuse annotations file.
#
# This file controls how reuse-tool finds copyright and license notices within
# source files.
# See https://reuse.software and https://github.com/fsfe/reuse-tool for more
# details.
# We currently use reuse-tool version 5.0.2.

version = 1

[[annotations]]
path = ["PULL_REQUEST_TEMPLATE.md"]
precedence = "override"
SPDX-FileCopyrightText = "© 2025 Nayan Patil <nayantsg@proton.me>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
