# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: CC-BY-SA-4.0
# ==-----------------------------------------------------------== #

body:
  - type: textarea
    id: discussion-field
    attributes:
      label: Tell us more.
      description: Explain your idea for Necronux in this field.
    validations:
      required: true
