# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: CC-BY-SA-4.0
# ==-----------------------------------------------------------== #

name: Proposed Changes (Direct Issue creation is not allowed)
description: As a user of Necronux, please create a Discussion first - do not use this template to create an Issue!
labels: ['state:needs-triage']
body:
  - type: markdown
    attributes:
      value: '# This form is for Necronux administrators only.'

  - type: markdown
    attributes:
      value: |
        **Stop!** This form is for the Necronux administrators only.
        If you're a user of Necronux, please create a GitHub Discussion.
        Please go back a step and select _Contributors Community_ instead of Issue.
        If you ignore these directions, you will be blocked from this repo.

  - type: textarea
    id: describe-proposed-changes
    attributes:
      label: Describe the proposed change(s).
      description: 'Do not report any security concerns here. Check our security policy for it.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: '# Reminder for administrators'

  - type: markdown
    attributes:
      value: 'Before submitting the issue, add the correct **category:** label.'
