# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: CC-BY-SA-4.0
# ==-----------------------------------------------------------== #

name: Notice Issue (Direct Issue creation is not allowed)
description: As a user of Necronux, please create a Discussion first - do not use this template to create an Issue!
labels: ['category:notice', 'state:meta']
body:
  - type: markdown
    attributes:
      value: '# This form is for Necronux administrators only.'

  - type: markdown
    attributes:
      value: |
        **Stop!** This form is for the Necronux administrators only.
        If you're a user of Necronux, please create a GitHub Discussion.
        Please go back a step and select _Contributors Community_ instead of Issue.
        If you ignore these directions, you will be blocked from this repo.

  - type: textarea
    id: notice
    attributes:
      label: Notice
      description: Please provide the notice.
    validations:
      required: true
