# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: CC-BY-SA-4.0
# ==-----------------------------------------------------------== #

name: Bug Report
description: Report a bug to help us improve!
labels: ["C-bug", "S-needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report!
  - type: checkboxes
    attributes:
      label: Please complete the following tasks
      options:
        - label: I have searched the [discussions](https://github.com/orgs/necronux/discussions)
          required: true
        - label: I have searched [open issues](https://github.com/search?q=org%3Anecronux+is%3Aissue+is%3Aopen) and [wont-fix issues](https://github.com/search?q=org%3Anecronux+label%3AS-wont-fix+is%3Aissue+is%3Aclosed) across the Necronux organization
          required: true
  - type: input
    id: stdschema_version
    attributes:
      label: Necronux Stdschema Version
      description: >
        Please provide the release number or commit hash of the version you're using.
        PLEASE DO NOT PUT "latest" HERE, use precise version.
    validations:
      required: false
  - type: input
    id: cli_app_version
    attributes:
      label: Necronux Cli App Version
      description: >
        Please provide the release number or commit hash of the version you're using.
        PLEASE DO NOT PUT "latest" HERE, use precise version.
    validations:
      required: false
  - type: input
    id: systeminfo
    attributes:
      label: (Optional) Relevant system information
      description: >
        If you cannot get Necronux to build or run on your machine, please include:
        the Rust version you're using (you can get this by running `cargo --version`)
        the operating system used, including its version
        e.g. Ubuntu 18.04, iOS 14, Windows 10
  - type: textarea
    id: steps
    attributes:
      label: What you did
      description: >
        Please describe how you arrived at the problem. If you can, consider providing a code snippet or link.
  - type: textarea
    id: problem
    attributes:
      label: What went wrong
      description: >
        If it's not clear, break this out into: what were you expecting? & what actually happened?
    validations:
      required: true
  - type: textarea
    id: additionalinfo
    attributes:
      label: Additional information
      description: >
        Please provide other information that can be used to further reproduce or isolate the problem.
        This commonly includes
        screenshots,
        logs,
        theories about what might be going wrong workarounds that you used,
        links to related bugs, PRs or discussions
  - type: textarea
    id: possible-solutions
    attributes:
      label: Possible Solution(s)
      description: >
        Not obligatory, but suggest a fix/reason for the bug,
        or ideas how to implement the addition or change.
