# ==-----------------------------------------------------------== #
# SPDX-FileCopyrightText: © 2025 Nayan Patil <nayantsg@proton.me>
#
# SPDX-License-Identifier: CC-BY-SA-4.0
# ==-----------------------------------------------------------== #

name: Roadmap Issue
description: A roadmap issue for an accepted feature.
body:
  - type: textarea
    id: highlevel
    attributes:
      label: High Level
      description: Please provide the overarching goal or idea.
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: Related threads & Feature Requests
      description: Please provide links to any relevant issues, threads, or discussions.
      placeholder: |
        - #123 Chats / Discussions
        - #456 User comments / annotations
    validations:
      required: false
